# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled4.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdnbmpK9mQXOG0Wts9YyySCBjKEuWwyG
"""

# Читаем библиотеку GeoPandas
import geopandas as gpd
import matplotlib.pyplot as plt

# Указываем путь к файлу
#shapefile_path = "C:/Py_Geo/shape/boundary-polygon-land.shp"

shapefile_path = 'boundary-polygon-land.shp'
print (shapefile_path)

# Читаем шейп-файл
dataframe = gpd.read_file(shapefile_path)

# Создаем карту
fig, ax = plt.subplots()

# Отображаем объекты шейп-файла на карте
dataframe.plot(ax=ax)

# Отображаем карту
plt.show()